---
all:
  children:
    molecule:
      hosts:
        molecule-fedora:
          ansible_connection: containers.podman.podman
          container_image: docker.io/library/python:3.14.7-slim-trixie
          container_command: sleep 1d
          container_privileged: false