---
all:
  children:
    molecule:
      hosts:
        molecule-fedora:
          ansible_connection: containers.podman.podman
          container_image: docker.io/library/ubuntu:24.04
          container_command: sleep 1d
          container_privileged: false